version: '3'
services:
  # sudo modprobe af_key -- needed kernel modul loading on host    
  vpn:
    image: hwdsl2/ipsec-vpn-server
    restart: always
    environment:
      - VPN_IPSEC_PSK=mypsk
      - VPN_USER=myuser
      - VPN_PASSWORD=mypass
    ports:
      - "500:500/udp"
      - "4500:4500/udp"
    networks:
      - vpn
    privileged: true
    volumes:
      - /lib/modules:/lib/modules:ro
    networks:
      vpn:
        ipv4_address: 172.16.238.253
  owncloud:
    image: owncloud:10.0.7
    restart: always
    volumes:
      - owncloud:/var/www/html
    networks:
      vpn:
        ipv4_address: 172.16.238.2
  portainer:
    image: portainer/portainer:1.16.4
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data
    networks:
      vpn:
        ipv4_address: 172.16.238.3
  gitea:
    image: gitea/gitea:1.3.2
    restart: always
    volumes:
      - gitea:/data
    depends_on:
      - gitea-db
    networks:
      vpn:
        ipv4_address: 172.16.238.4
  gitea-db:
    image: mariadb:10
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootpw
      - MYSQL_DATABASE=gitea
      - MYSQL_USER=gituser
      - MYSQL_PASSWORD=dbpass
    volumes:
      - gitea-db:/var/lib/mysql
    networks:
      vpn:
        ipv4_address: 172.16.238.5
volumes:
  owncloud:
  portainer:
  gitea-db:
  gitea:
networks:
  vpn:
    ipam:
     config:
       -  subnet: 172.16.238.0/24
    
